matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python: "2.7"
      sudo: false
    - os: linux
      dist: bionic
      language: python
      python: "3.6"
      sudo: false

addons:
  apt:
    packages:
      - festival festvox-us1 festlex-cmu festlex-poslex espeak-ng

install:
  - pip install --upgrade pip
  - pip install .[test]

script:
  - phonemize --version
  - pytest ./test -v

cache:
  - pip

notifications:
  email: false
