dist: bionic
addons:
  apt:
    packages:
      - festival festvox-us1 festlex-cmu festlex-poslex espeak-ng

language: python

# no need of git history
git:
  depth: 1

# test only the master branch
branches:
  only:
    - master

install:
  - pip install --upgrade pip
  - pip install pytest-cov coverage
  - pip install .[test]

script:
  - phonemize --version
  - pytest ./test -v

after_success:
  - codecov

cache:
  - pip

notifications:
  email: false
