language: python

# run on Travis 'new' container-based infrastructure
sudo: false

# no need of git history
git:
  depth: 1

# test only the master branch
branches:
  only:
    - master

addons:
  apt:
    packages:
      - festival festvox-us1 festlex-cmu festlex-poslex espeak-ng

install:
  - pip install --upgrade pip
  - pip install pytest-cov coverage
  - pip install .[test]

script:
  - phonemize --version
  - pytest ./test -v

after_success:
  - codecov

cache:
  - pip

notifications:
  email: false
