dist: bionic
addons:
  apt:
    packages:
      - festival festvox-us1 festlex-cmu festlex-poslex espeak-ng mbrola mbrola-fr1

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

# no need of git history
git:
  depth: 1

# test only the master branch
branches:
  only:
    - master

install:
  - pip install --upgrade pip
  - pip install pytest-cov codecov
  - pip install .[test]

script:
  - phonemize --version
  - python setup.py test

after_success:
  - codecov

cache:
  - pip

notifications:
  email: false
