matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "2.7"
      sudo: false
    - os: linux
      dist: trusty
      language: python
      python: "3.6"
      sudo: false

addons:
  apt:
    packages:
      - festival festvox-us1 festlex-cmu festlex-poslex espeak

install:
  - pip install --upgrade pip
  - pip install joblib pytest
  - python setup.py build
  - python setup.py install

script:
  - echo "This is a test." | festival --tts
  - phonemize --version
  - pytest ./test -v

cache:
  - pip

notifications:
  email: false
